version: '3'

services:

  discovery:
    build: discovery
    container_name: discovery
    ports:
      - "8761:8761"

  zool:
    build: zool-gateway
    container_name: zool
    ports:
      - "7777:7777"
    depends_on:
        - rabbitmq
        - discovery

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

  order-command:
    build: order-command
    depends_on:
        - rabbitmq
        - discovery

  order-query:
    build: order-query
    depends_on:
        - rabbitmq
        - discovery
        - order-command

  driver-command:
    build: driver-command
    depends_on:
        - rabbitmq
        - discovery

  driver-query:
    build: driver-query
    depends_on:
        - rabbitmq
        - discovery
        - driver-command
