taxi:
  staticResources: ${static-resources}

logging:
  level:
    com:
      epam: DEBUG

server:
  port: 7777

spring:
  output:
    ansi:
      enabled: always
  application:
    name: zool
  rabbitmq:
    host: ${rabbitmq-host}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${discovery-host}:8761/eureka/

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    order-query:
        path: /order-query/**
        serviceId: order-query
        stripPrefix: true
        sensitiveHeaders:

    order-command:
        path: /order-command/**
        serviceId: order-command
        stripPrefix: true
        sensitiveHeaders:

    driver-query:
        path: /driver-query/**
        serviceId: driver-query
        stripPrefix: true
        sensitiveHeaders:

    driver-command:
        path: /driver-command/**
        serviceId: driver-command
        stripPrefix: true
        sensitiveHeaders:


#
#    account-service:
#        path: /accounts/**
#        url: http://auth-service:5000
#        stripPrefix: false
#        sensitiveHeaders:
#
