logging:
  level:
    com:
      epam: DEBUG
#    org:
#      axonframework: DEBUG

server:
  port: 9090

spring:
  output:
    ansi:
      enabled: always
  application:
    name: order-command
  rabbitmq:
    host: ${rabbitmq-host}
  h2:
    console:
      enabled: true

axon:
  amqp:
    exchange: TaxiOrderExchange
  distributed:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defailtZone: http://${discovery-host}:8761/eureka/

