logging:
  level:
    com:
      epam: DEBUG
#    org:
#      axonframework: DEBUG

server:
  port: 9292

spring:
  output:
    ansi:
      enabled: always
  application:
    name: driver-command
  rabbitmq:
    host: ${rabbitmq-host}
  h2:
    console:
      enabled: true

axon:
  distributed:
    enabled: true
  amqp:
    exchange: TaxiExchange
  eventhandling:
    processors:
      taxiExchange:
        source: taxiExchange

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defailtZone: http://${discovery-host}:8761/eureka/

