server:
  port: 8761

spring:
  application:
    name: discovery
  output:
    ansi:
      enabled: always

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0