logging:
  level:
    com:
      epam: DEBUG

server:
  port: 9191

spring:
  output:
    ansi:
      enabled: always
  application:
    name: order-query
  rabbitmq:
    host: ${rabbitmq-host}

axon:
  eventhandling:
    processors:
      taxiOrderEvents:
        source: taxiOrderEvents

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${discovery-host}:8761/eureka/
